import React, { useState, useEffect } from 'react';
import { LanguageConfig, FlashcardItem, INITIAL_FLASHCARDS } from '../../data/languageCurriculum';
import { Layers, Volume2, RotateCw, Sparkles, Check, Flame, ChevronLeft, ChevronRight, BookOpen, Lightbulb } from 'lucide-react';
import { playNativePronunciation } from '../../utils/audioPlayer';
import { haptics } from '../../utils/haptics';

interface FlashcardsViewProps {
  currentLanguage: LanguageConfig;
}

export const FlashcardsView: React.FC<FlashcardsViewProps> = ({ currentLanguage }) => {
  const [cards, setCards] = useState<FlashcardItem[]>(() => {
    const forLang = INITIAL_FLASHCARDS.filter(c => c.languageId === currentLanguage.id);
    return forLang.length > 0 ? forLang : INITIAL_FLASHCARDS;
  });

  const [currentIndex, setCurrentIndex] = useState<number>(0);
  const [isFlipped, setIsFlipped] = useState<boolean>(false);
  const [newDeckTopic, setNewDeckTopic] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  // Sync flashcards when language changes
  useEffect(() => {
    const forLang = INITIAL_FLASHCARDS.filter(c => c.languageId === currentLanguage.id);
    setCards(forLang.length > 0 ? forLang : INITIAL_FLASHCARDS);
    setCurrentIndex(0);
    setIsFlipped(false);
  }, [currentLanguage.id]);

  const activeCard = cards[currentIndex] || cards[0];

  // Audio Playback with Android hardening
  const handleSpeak = (text: string, phoneticHint?: string) => {
    playNativePronunciation(text, currentLanguage.id, { 
      rate: 0.85,
      phoneticHint: phoneticHint || activeCard?.phoneticHindi || activeCard?.phonetic
    });
  };

  const handleNext = () => {
    if (cards.length === 0) return;
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev + 1) % cards.length);
  };

  const handlePrev = () => {
    if (cards.length === 0) return;
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
  };

  const handleRate = (deltaStreak: number) => {
    if (!activeCard) return;
    const newStreak = Math.max(0, activeCard.streak + deltaStreak);

    if (deltaStreak > 0) {
      if (newStreak >= 5) {
        haptics.milestone();
      } else {
        haptics.success();
      }
    } else {
      haptics.warning();
    }

    const updated = cards.map((c, idx) => {
      if (idx === currentIndex) {
        return {
          ...c,
          streak: newStreak
        };
      }
      return c;
    });
    setCards(updated);
    handleNext();
  };

  // Generate Custom Deck via Gemini Backend
  const handleGenerateDeck = async () => {
    if (!newDeckTopic.trim() || isGenerating) return;

    setIsGenerating(true);
    try {
      const res = await fetch('/api/generate-cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          language: currentLanguage.id,
          topic: newDeckTopic,
          count: 5
        })
      });

      const json = await res.json();
      if (json.success && json.data?.cards) {
        const generated: FlashcardItem[] = json.data.cards.map((c: any, idx: number) => ({
          id: `gen-${Date.now()}-${idx}`,
          languageId: currentLanguage.id,
          front: c.front,
          phoneticHindi: c.phoneticHindi || c.phonetic,
          phonetic: c.phonetic,
          backHindi: c.backHindi || c.back,
          back: c.back,
          categoryHindi: c.categoryHindi || '✨ नए AI कार्ड्स',
          category: c.category || newDeckTopic,
          level: 'Beginner',
          exampleSentence: c.exampleSentence || {
            target: c.front,
            phoneticHindi: c.phoneticHindi || c.phonetic,
            phonetic: c.phonetic,
            translationHindi: c.backHindi || c.back,
            translation: c.back
          },
          notesHindi: c.notesHindi || 'AI द्वारा निर्मित अभ्यास कार्ड',
          notes: c.notes || 'Generated by PolyGlot AI',
          streak: 0
        }));

        setCards([...generated, ...cards]);
        setCurrentIndex(0);
        setIsFlipped(false);
        setNewDeckTopic('');
      }
    } catch (err) {
      console.error('Deck generator error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Worker Friendly Hindi Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-850 to-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Layers className="w-5 h-5 text-amber-400" />
            <span className="text-xs font-bold text-amber-400 uppercase tracking-wider">
              श्रमवीर शब्दावली अभ्यास • याद रखने के कार्ड (Flashcards)
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            याद रखने के कार्ड्स ({currentLanguage.name})
          </h2>
          <p className="text-xs sm:text-sm text-slate-300 mt-1">
            कार्ड पर टैप करके पलटें, देवनागरी उच्चारण पढ़ें और स्पीकर दबाकर सही आवाज सुनें।
          </p>
        </div>

        {/* Generate Custom Deck Input (सरल हिन्दी में) */}
        <div className="flex items-center gap-2 bg-slate-950 p-2 rounded-xl border border-slate-800">
          <input
            type="text"
            value={newDeckTopic}
            onChange={(e) => setNewDeckTopic(e.target.value)}
            placeholder="जैसे: एयरपोर्ट, अस्पताल, औजार..."
            className="px-3 py-1.5 bg-slate-900 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500 w-44 sm:w-52"
          />
          <button
            onClick={handleGenerateDeck}
            disabled={isGenerating || !newDeckTopic.trim()}
            className="px-3 py-1.5 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-950 font-bold text-xs rounded-lg transition-colors cursor-pointer flex items-center gap-1.5 shadow-md shadow-amber-500/20 shrink-0"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>{isGenerating ? 'बन रहा है...' : 'नया AI कार्ड'}</span>
          </button>
        </div>
      </div>

      {/* Main Flashcard Interactive Player */}
      {cards.length > 0 && activeCard ? (
        <div className="max-w-2xl mx-auto space-y-5">
          
          {/* Card Header stats */}
          <div className="flex items-center justify-between px-2 text-xs text-slate-300">
            <div className="flex items-center gap-2">
              <span className="font-mono font-bold text-amber-400 text-sm">
                कार्ड {currentIndex + 1} / {cards.length}
              </span>
              <span>•</span>
              <span className="bg-slate-850 px-2.5 py-0.5 rounded-full text-xs text-amber-300 border border-slate-700 font-semibold">
                {activeCard.categoryHindi || activeCard.category}
              </span>
            </div>

            <div className="flex items-center gap-1.5 font-bold text-amber-400">
              <Flame className="w-4 h-4" />
              <span>याद रखने का स्कोर: {activeCard.streak}</span>
            </div>
          </div>

          {/* Flashcard Box with Flip toggle */}
          <div
            onClick={() => setIsFlipped(!isFlipped)}
            className="relative min-h-[300px] sm:min-h-[340px] bg-slate-900 border-2 border-slate-800 hover:border-amber-500/60 rounded-3xl p-6 sm:p-8 shadow-2xl transition-all cursor-pointer flex flex-col justify-between select-none group"
          >
            {/* Top row of card */}
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-emerald-400 bg-emerald-400/10 px-3 py-1 rounded-full border border-emerald-500/20">
                {isFlipped ? '🔄 पीछे का भाग: हिन्दी अर्थ व वाक्य' : '❓ आगे का भाग: विदेशी शब्द'}
              </span>

              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleSpeak(activeCard.front);
                }}
                className="p-2.5 rounded-xl bg-amber-500 text-slate-950 hover:bg-amber-400 font-bold transition-transform active:scale-95 cursor-pointer shadow-md flex items-center gap-1.5 text-xs"
                title="सही उच्चारण सुनें"
              >
                <Volume2 className="w-4 h-4" />
                <span>बोलकर सुनें</span>
              </button>
            </div>

            {/* Middle Content */}
            <div className="text-center py-5 space-y-3">
              {!isFlipped ? (
                <>
                  <div 
                    className="text-3xl sm:text-4xl font-black text-white tracking-tight leading-relaxed"
                    dir={currentLanguage.direction}
                  >
                    {activeCard.front}
                  </div>
                  
                  <div className="space-y-1">
                    <div className="text-base sm:text-lg font-mono text-amber-300 font-bold">
                      बोलें: {activeCard.phoneticHindi || activeCard.phonetic}
                    </div>
                    {activeCard.phoneticHindi && activeCard.phonetic !== activeCard.phoneticHindi && (
                      <div className="text-xs text-slate-400 font-mono">
                        ({activeCard.phonetic})
                      </div>
                    )}
                  </div>

                  <div className="text-xs text-slate-400 pt-3 flex items-center justify-center gap-1.5">
                    <RotateCw className="w-4 h-4 group-hover:rotate-180 transition-transform duration-500 text-amber-400" />
                    <span className="text-amber-400/90 font-medium">हिन्दी अर्थ देखने के लिए कार्ड पर कहीं भी दबाएं</span>
                  </div>
                </>
              ) : (
                <div className="space-y-4">
                  <div className="space-y-1">
                    <div className="text-2xl sm:text-3xl font-black text-emerald-400">
                      {activeCard.backHindi || activeCard.back}
                    </div>
                    {activeCard.backHindi && activeCard.back !== activeCard.backHindi && (
                      <div className="text-xs text-slate-400">
                        ({activeCard.back})
                      </div>
                    )}
                  </div>

                  {activeCard.exampleSentence && (
                    <div className="p-4 rounded-xl bg-slate-950/90 border border-slate-800 space-y-1.5 max-w-lg mx-auto text-left">
                      <div className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1">
                        <BookOpen className="w-3.5 h-3.5" />
                        <span>काम पर प्रयोग (Example Sentence):</span>
                      </div>
                      <div className="text-sm font-bold text-white" dir={currentLanguage.direction}>
                        {activeCard.exampleSentence.target}
                      </div>
                      <div className="text-xs text-amber-300 font-mono font-bold">
                        उच्चारण: {activeCard.exampleSentence.phoneticHindi || activeCard.exampleSentence.phonetic}
                      </div>
                      <div className="text-xs text-emerald-300 font-medium">
                        अर्थ: "{activeCard.exampleSentence.translationHindi || activeCard.exampleSentence.translation}"
                      </div>
                    </div>
                  )}

                  {(activeCard.notesHindi || activeCard.notes) && (
                    <div className="text-xs text-slate-300 max-w-md mx-auto p-2.5 rounded-lg bg-amber-500/10 border border-amber-500/20 text-left flex items-start gap-2">
                      <Lightbulb className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                      <span><strong>श्रमवीर सलाह:</strong> {activeCard.notesHindi || activeCard.notes}</span>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Bottom Progress Bar */}
            <div className="w-full bg-slate-950 rounded-full h-2 overflow-hidden">
              <div
                className="bg-amber-500 h-full transition-all duration-300"
                style={{ width: `${((currentIndex + 1) / cards.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Controls below card - Worker Friendly Actions */}
          <div className="flex items-center justify-between gap-2">
            <button
              onClick={handlePrev}
              className="p-3 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 rounded-xl transition-colors cursor-pointer"
              title="पिछला कार्ड (Previous)"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>

            {/* SRS Feedback Buttons with clear Hindi meanings */}
            <div className="flex items-center gap-2 flex-1 justify-center max-w-md">
              <button
                onClick={() => handleRate(-1)}
                className="flex-1 py-2.5 px-3 bg-rose-950/40 hover:bg-rose-900/60 border border-rose-800/40 text-rose-300 font-bold text-xs rounded-xl transition-colors cursor-pointer text-center"
              >
                ❌ मुश्किल है
              </button>
              <button
                onClick={() => handleRate(1)}
                className="flex-1 py-2.5 px-3 bg-emerald-950/40 hover:bg-emerald-900/60 border border-emerald-800/40 text-emerald-300 font-bold text-xs rounded-xl transition-colors cursor-pointer text-center"
              >
                👍 याद हुआ (+1)
              </button>
              <button
                onClick={() => handleRate(2)}
                className="flex-1 py-2.5 px-3 bg-blue-950/40 hover:bg-blue-900/60 border border-blue-800/40 text-blue-300 font-bold text-xs rounded-xl transition-colors cursor-pointer text-center"
              >
                🌟 पक्का याद (+2)
              </button>
            </div>

            <button
              onClick={handleNext}
              className="p-3 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 rounded-xl transition-colors cursor-pointer"
              title="अगला कार्ड (Next)"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

        </div>
      ) : (
        <div className="p-12 text-center bg-slate-900 border border-slate-800 rounded-2xl">
          <p className="text-sm text-slate-400">इस भाषा के लिए कोई फ्लैशकार्ड नहीं मिला।</p>
        </div>
      )}

    </div>
  );
};
