import React, { useState } from 'react';
import { LanguageConfig, FlashcardItem, INITIAL_FLASHCARDS } from '../../data/languageCurriculum';
import { Layers, Volume2, RotateCw, Plus, Sparkles, Check, X, Flame, ChevronLeft, ChevronRight } from 'lucide-react';
import { playNativePronunciation } from '../../utils/audioPlayer';

interface FlashcardsViewProps {
  currentLanguage: LanguageConfig;
}

export const FlashcardsView: React.FC<FlashcardsViewProps> = ({ currentLanguage }) => {
  const [cards, setCards] = useState<FlashcardItem[]>(() => {
    const forLang = INITIAL_FLASHCARDS.filter(c => c.languageId === currentLanguage.id);
    return forLang.length > 0 ? forLang : INITIAL_FLASHCARDS;
  });

  const [currentIndex, setCurrentIndex] = useState<number>(0);
  const [isFlipped, setIsFlipped] = useState<boolean>(false);
  const [newDeckTopic, setNewDeckTopic] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  const activeCard = cards[currentIndex] || cards[0];

  // Audio Playback
  const handleSpeak = (text: string) => {
    playNativePronunciation(text, currentLanguage.id, { rate: 0.85 });
  };

  const handleNext = () => {
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev + 1) % cards.length);
  };

  const handlePrev = () => {
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
  };

  const handleRate = (deltaStreak: number) => {
    if (!activeCard) return;
    const updated = cards.map((c, idx) => {
      if (idx === currentIndex) {
        return {
          ...c,
          streak: Math.max(0, c.streak + deltaStreak)
        };
      }
      return c;
    });
    setCards(updated);
    handleNext();
  };

  // Generate Custom Deck via Gemini Backend
  const handleGenerateDeck = async () => {
    if (!newDeckTopic.trim() || isGenerating) return;

    setIsGenerating(true);
    try {
      const res = await fetch('/api/generate-cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          language: currentLanguage.id,
          topic: newDeckTopic,
          count: 5
        })
      });

      const json = await res.json();
      if (json.success && json.data?.cards) {
        const generated: FlashcardItem[] = json.data.cards.map((c: any, idx: number) => ({
          id: `gen-${Date.now()}-${idx}`,
          languageId: currentLanguage.id,
          front: c.front,
          phonetic: c.phonetic,
          back: c.back,
          category: c.category || newDeckTopic,
          level: 'Beginner',
          exampleSentence: c.exampleSentence || {
            target: c.front,
            phonetic: c.phonetic,
            translation: c.back
          },
          notes: c.notes || 'Generated by PolyGlot AI',
          streak: 0
        }));

        setCards([...generated, ...cards]);
        setCurrentIndex(0);
        setIsFlipped(false);
        setNewDeckTopic('');
      }
    } catch (err) {
      console.error('Deck generator error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-850 to-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Layers className="w-5 h-5 text-amber-400" />
            <span className="text-xs font-bold text-amber-400 uppercase tracking-wider">
              Smart Spaced Repetition (SRS)
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            Flashcards & Vocabulary Drills
          </h2>
          <p className="text-xs sm:text-sm text-slate-300 mt-1">
            Master high-frequency native vocabulary and authentic dialectal idioms with audio feedback.
          </p>
        </div>

        {/* Generate Custom Deck Input */}
        <div className="flex items-center gap-2 bg-slate-950 p-2 rounded-xl border border-slate-800">
          <input
            type="text"
            value={newDeckTopic}
            onChange={(e) => setNewDeckTopic(e.target.value)}
            placeholder="e.g. Airport, Restaurant, Business..."
            className="px-3 py-1.5 bg-slate-900 border border-slate-850 rounded-lg text-xs text-white placeholder-slate-400 focus:outline-none focus:border-amber-500 w-44 sm:w-56"
          />
          <button
            onClick={handleGenerateDeck}
            disabled={isGenerating || !newDeckTopic.trim()}
            className="px-3 py-1.5 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-950 font-bold text-xs rounded-lg transition-colors cursor-pointer flex items-center gap-1.5 shadow-md shadow-amber-500/20"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>{isGenerating ? 'Creating...' : 'AI Deck'}</span>
          </button>
        </div>
      </div>

      {/* Main Flashcard Interactive Player */}
      {cards.length > 0 && activeCard ? (
        <div className="max-w-2xl mx-auto space-y-5">
          
          {/* Card Header stats */}
          <div className="flex items-center justify-between px-2 text-xs text-slate-400">
            <div className="flex items-center gap-2">
              <span className="font-mono font-bold text-amber-400">
                Card {currentIndex + 1} of {cards.length}
              </span>
              <span>•</span>
              <span className="bg-slate-850 px-2 py-0.5 rounded text-[11px] text-slate-300 border border-slate-800">
                {activeCard.category}
              </span>
            </div>

            <div className="flex items-center gap-1.5 font-bold text-amber-400">
              <Flame className="w-4 h-4" />
              <span>Streak: {activeCard.streak}</span>
            </div>
          </div>

          {/* Flashcard Box with Flip toggle */}
          <div
            onClick={() => setIsFlipped(!isFlipped)}
            className="relative min-h-[300px] sm:min-h-[340px] bg-slate-900 border-2 border-slate-800 hover:border-amber-500/60 rounded-3xl p-6 sm:p-8 shadow-2xl transition-all cursor-pointer flex flex-col justify-between select-none group"
          >
            {/* Top row of card */}
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-400/10 px-2.5 py-0.5 rounded-full border border-emerald-500/20">
                {isFlipped ? 'Answer Side (उत्तर)' : 'Prompt Side (प्रश्न)'}
              </span>

              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleSpeak(activeCard.front);
                }}
                className="p-2 rounded-xl bg-slate-800/80 hover:bg-amber-500 hover:text-slate-950 text-slate-300 transition-colors cursor-pointer"
                title="Pronounce Word"
              >
                <Volume2 className="w-4 h-4" />
              </button>
            </div>

            {/* Middle Content */}
            <div className="text-center py-6 space-y-3">
              {!isFlipped ? (
                <>
                  <div 
                    className="text-3xl sm:text-4xl font-black text-white tracking-tight leading-relaxed"
                    dir={currentLanguage.direction}
                  >
                    {activeCard.front}
                  </div>
                  <div className="text-base sm:text-lg font-mono text-amber-400 font-bold">
                    {activeCard.phonetic}
                  </div>
                  <div className="text-xs text-slate-400 pt-2 flex items-center justify-center gap-1">
                    <RotateCw className="w-3.5 h-3.5 group-hover:rotate-180 transition-transform duration-500 text-amber-400" />
                    <span>Click anywhere to flip card</span>
                  </div>
                </>
              ) : (
                <div className="space-y-4">
                  <div className="text-2xl sm:text-3xl font-black text-emerald-400">
                    {activeCard.back}
                  </div>

                  {activeCard.exampleSentence && (
                    <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1.5 max-w-lg mx-auto text-left">
                      <div className="text-xs font-bold text-amber-400 uppercase tracking-wider">
                        Example Usage:
                      </div>
                      <div className="text-sm font-bold text-white" dir={currentLanguage.direction}>
                        {activeCard.exampleSentence.target}
                      </div>
                      <div className="text-xs text-amber-400/90 font-mono">
                        {activeCard.exampleSentence.phonetic}
                      </div>
                      <div className="text-xs text-slate-300 italic">
                        "{activeCard.exampleSentence.translation}"
                      </div>
                    </div>
                  )}

                  {activeCard.notes && (
                    <div className="text-xs text-slate-400 max-w-md mx-auto">
                      💡 {activeCard.notes}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Bottom Progress Bar */}
            <div className="w-full bg-slate-950 rounded-full h-1.5 overflow-hidden">
              <div
                className="bg-amber-500 h-full transition-all duration-300"
                style={{ width: `${((currentIndex + 1) / cards.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Controls below card */}
          <div className="flex items-center justify-between gap-2">
            <button
              onClick={handlePrev}
              className="p-3 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 rounded-xl transition-colors cursor-pointer"
              title="Previous Card"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>

            {/* SRS Feedback Buttons */}
            <div className="flex items-center gap-2 flex-1 justify-center max-w-md">
              <button
                onClick={() => handleRate(-1)}
                className="flex-1 py-2.5 px-3 bg-rose-950/40 hover:bg-rose-900/60 border border-rose-800/40 text-rose-300 font-bold text-xs rounded-xl transition-colors cursor-pointer"
              >
                Hard (-1)
              </button>
              <button
                onClick={() => handleRate(1)}
                className="flex-1 py-2.5 px-3 bg-emerald-950/40 hover:bg-emerald-900/60 border border-emerald-800/40 text-emerald-300 font-bold text-xs rounded-xl transition-colors cursor-pointer"
              >
                Good (+1)
              </button>
              <button
                onClick={() => handleRate(2)}
                className="flex-1 py-2.5 px-3 bg-blue-950/40 hover:bg-blue-900/60 border border-blue-800/40 text-blue-300 font-bold text-xs rounded-xl transition-colors cursor-pointer"
              >
                Easy (+2)
              </button>
            </div>

            <button
              onClick={handleNext}
              className="p-3 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 rounded-xl transition-colors cursor-pointer"
              title="Next Card"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

        </div>
      ) : (
        <div className="p-12 text-center bg-slate-900 border border-slate-800 rounded-2xl">
          <p className="text-sm text-slate-400">No flashcards found for this language.</p>
        </div>
      )}

    </div>
  );
};
